DROP TABLE FORM_LIST;
DROP SEQUENCE FORM_LIST_ID_SEQ;
DROP TABLE MEMBER_FAVORITE;
DROP SEQUENCE MEMBER_FAVORITE_ID_SEQ;
DROP TABLE SPACE_COMMENT;
DROP SEQUENCE SPACE_COMMENT_ID_SEQ;
DROP TABLE MEMBER_COMMENT;
DROP SEQUENCE MEMBER_COMMENT_ID_SEQ;
DROP TABLE SPACE_PHOTO;
DROP SEQUENCE SPACE_PHOTO_ID_SEQ;
DROP TABLE ORDER_DETAIL;
DROP SEQUENCE ORDER_DETAIL_ID_SEQ;
DROP TABLE SPACE_DETAIL;
DROP SEQUENCE SPACE_DETAIL_ID_SEQ;
DROP TABLE ORDER_MASTER;
DROP SEQUENCE ORDER_MASTER_ID_SEQ;
DROP TABLE SPACE;
DROP SEQUENCE SPACE_ID_SEQ;
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_ID_SEQ;
DROP TABLE EMP;
DROP SEQUENCE EMP_ID_SEQ;


ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'yyyy-mm-dd hh24:mi:ss'; 


---------------------------------------------------------
CREATE TABLE MEMBER (
MEMBER_ID  VARCHAR2(20) NOT NULL,
MEMBER_ACCOUNT   VARCHAR2(20) NOT NULL,
MEMBER_PASSWORD   VARCHAR2(20) NOT NULL,
MEMBER_NAME   VARCHAR2(90) NOT NULL,
MEMBER_NICKNAME   VARCHAR2(30) NOT NULL,
MEMBER_EMAIL   VARCHAR2(90) NOT NULL,
MEMBER_PHOTO   BLOB,
MEMBER_PHONE   VARCHAR2(20),
MEMBER_ADDRESS   VARCHAR2(120),
MEMBER_BIRTH  DATE,
MEMBER_SEX VARCHAR2(3),
MEMBER_COUNTRY   VARCHAR2(30),
MEMBER_SIGNUP_DATE   DATE NOT NULL,
MEMBER_AUTH   NUMBER(4) NOT NULL,
MEMBER_STATUS   CHAR(1) NOT NULL,
MEMBER_STATUS_EMP   VARCHAR2(20),
MEMBER_STATUS_COMM   VARCHAR2(100),
MEMBER_ONLINE   CHAR(1) NOT NULL,
CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
);

CREATE SEQUENCE MEMBER_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

--------------------------------------------------------------------
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'am6319146', 'ZHcoPk', '馬全德', '馬哥', 'gbauer9@tibame.edu.com', '0911-332233', '新北市中和區','1990-05-04', 'M', '美國','2015-08-12', 1, 'O', 'N' );
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'bk53292916a', 'IML0bFfYUTo', '張互賓', '互賓', 'svolkes8@gmail.com', '0922-778877', '台北市中正區', '1969-03-25', 'M', '台灣','2016-04-27', 2, 'O', 'N' );
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'tinsdgfl8421', '5354e1r48gd', '劉宜婷', '宜婷', 'yitibkjoldk511@tibame.edu.com', '0925-587786', '新北市中和區', '1981-05-03', 'F', '台灣','2019-05-05', 2, 'O', 'N' );
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'lasjoir41', '56cvb41n89rt', '詹姆士', '喇叭詹', 'lejdflkgd1459we@gmail.com', '0915-547865', '新北市三重區', '1990-05-11', 'M', '台灣','2020-03-23', 2, 'O', 'N' );
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'wufsklr989', '48df1g8gft', '黃彬華', '彬華', 'hundfg4789@tibame.edu.com', '0925-452722', '桃園市中壢區', '1992-08-17', 'M', '英國','2020-09-05', 1, 'P', 'N' );
INSERT INTO MEMBER ( MEMBER_ID, MEMBER_ACCOUNT, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_PHONE, MEMBER_ADDRESS, MEMBER_BIRTH, MEMBER_SEX, MEMBER_COUNTRY, MEMBER_SIGNUP_DATE, MEMBER_AUTH, MEMBER_STATUS, MEMBER_ONLINE  ) VALUES ( 'MEM' || lpad(MEMBER_ID_SEQ.NEXTVAL, 5, '0' ), 'jbiopgs25689', 'we87487dd', '馬英九', '小九', 'jigksdiofe454@gmail.com', '0973-894815', '新北市蘆洲區', '1995-07-02', 'M', '台灣','2020-09-11', 1, 'B', 'N' );
--------------------------------------------------------------------

CREATE TABLE EMP (
EMP_ID  VARCHAR2(20) NOT NULL,
EMP_ACCOUNT   VARCHAR2(20) NOT NULL,
EMP_PASSWORD   VARCHAR2(20) NOT NULL,
EMP_NAME   VARCHAR2(90) NOT NULL,
EMP_NICKNAME   VARCHAR2(30) NOT NULL,
EMP_EMAIL   VARCHAR2(90) NOT NULL,
EMP_PHOTO   BLOB,
EMP_PHONE   VARCHAR2(20),
EMP_ADDRESS   VARCHAR2(120) NOT NULL,
EMP_BIRTH  DATE,
EMP_SEX VARCHAR2(3),
EMP_COUNTRY   VARCHAR2(30),
EMP_HIRE_DATE   DATE NOT NULL,
EMP_JOB   VARCHAR2(30) NOT NULL,
EMP_AUTH   NUMBER(4) NOT NULL,
EMP_STATUS   CHAR(1) NOT NULL,
EMP_ONLINE   CHAR(1) NOT NULL,
CONSTRAINT EMP_PK PRIMARY KEY (EMP_ID)
);

CREATE SEQUENCE EMP_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
----------------------------------------------------------------------
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), '1', '1', '何弋柏', '弋柏', 'mcomport0@gmail.com', '0912-345678', '台北市士林區', '1992/11/17', 'M', '澳洲', '2011/02/21', '後端工程師', 1, 'O', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), '2', '2', '吳永志', '大吳', 'fcatterick1@tibame.edu.com', '0987-654321', '台北市松山區', '1982/09/24', 'M', '台灣', '2012/10/02', '職訓人員', 1, 'P', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), '3', '3', '吳冠宏', '小吳', 'etorbard2@tibame.edu.com', '0978-223355', '新北市汐止區', '1985/03/03', 'M', '台灣', '2015/09/18', '客服人員', 2, 'L', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), '4', '4', '楊乃文', '小楊', '415sf18@tibame.edu.com', '0965-752752', '台北市南港區', '1996/03/03', 'F', '台灣', '2018/11/18', '客服人員', 1, 'O', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), '5', '5', '何小明', '小明', 'Z748949615eqf@gmail.com', '0972-174555', '台北市萬華區', '1995/11/17', 'M', '台灣', '2019/05/11', '後端工程師', 1, 'O', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), 'QQ', 'QQ', 'QQ', 'QQ', 'Z748949615eqf@gmail.com', '0972-174555', '台北市萬華區', '1995/11/17', 'M', '台灣', '2019/05/11', '後端工程師', 1, 'O', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), 'CC', 'CC', 'CC', 'CC', 'Z748949615eqf@gmail.com', '0972-174555', '台北市萬華區', '1995/11/17', 'M', '台灣', '2019/05/11', '後端工程師', 1, 'O', 'N');
INSERT INTO EMP ( EMP_ID, EMP_ACCOUNT, EMP_PASSWORD, EMP_NAME, EMP_NICKNAME, EMP_EMAIL, EMP_PHONE, EMP_ADDRESS, EMP_BIRTH, EMP_SEX, EMP_COUNTRY, EMP_HIRE_DATE, EMP_JOB, EMP_AUTH, EMP_STATUS, EMP_ONLINE) values ('EMP' || lpad(EMP_ID_SEQ.NEXTVAL, 5, '0' ), 'Warren0816', '888888', '張期徫', '新鮮的肝', 'akemo2959@gmail.com', '0905-577857', '台北市林口區', '1988/08/16', 'M', '台灣', '2019/05/11', '菜焦阿', 1, 'O', 'N');
--------------------------------------------------------------------

CREATE TABLE SPACE(
SPACE_ID  VARCHAR2(20) NOT NULL,
MEMBER_ID   VARCHAR2(20) NOT NULL,
EMP_ID   VARCHAR2(20) NOT NULL,
SPACE_ADDRESS   VARCHAR2(120) NOT NULL,
SPACE_LNG   DECIMAL(30,20),
SPACE_LAT   DECIMAL(30,20),
SPACE_NAME   VARCHAR2(90) NOT NULL,
SPACE_TEXT   CLOB,
SPACE_TYPE   VARCHAR2(500),
SPACE_EQUMENT   VARCHAR2(500),
SPACE_CONTAIN   VARCHAR2(10) NOT NULL,
SPACE_RULE CLOB ,
SPACE_REFUND CLOB ,
SPACE_STATUS   CHAR(1) NOT NULL,
SPACE_SIGNUP_DATE  DATE NOT NULL,
SPACE_ONSALE_DATE   DATE,
SPACE_OFFSALE_DATE   DATE,
SPACE_STATUS_EMP   VARCHAR2(20),
SPACE_STATUS_COMM   VARCHAR2(100),
CONSTRAINT SPACE_PK PRIMARY KEY (SPACE_ID),
CONSTRAINT SPACE_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
CONSTRAINT SPACE_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMP (EMP_ID)
);

CREATE SEQUENCE SPACE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
------------------------------------------------------------------------------
INSERT INTO SPACE ( SPACE_ID, MEMBER_ID,EMP_ID, SPACE_ADDRESS, SPACE_NAME, SPACE_TYPE, SPACE_EQUMENT, SPACE_CONTAIN, SPACE_RULE, SPACE_REFUND, SPACE_STATUS, SPACE_SIGNUP_DATE, SPACE_ONSALE_DATE ) VALUES ( 'SPACE' || lpad(SPACE_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00003', 'EMP00003', '台北市大安區復興南路一段279巷33號', '藝文空間活動場地', '攝影棚', '冷氣', '10', '租借單位或團體應盡善良使用人之責任。','24小時內取消您的預定', 'T', '2019/11/23', '2019/11/24' );
INSERT INTO SPACE ( SPACE_ID, MEMBER_ID,EMP_ID, SPACE_ADDRESS, SPACE_NAME, SPACE_TYPE, SPACE_EQUMENT, SPACE_CONTAIN, SPACE_RULE, SPACE_REFUND, SPACE_STATUS, SPACE_SIGNUP_DATE, SPACE_ONSALE_DATE ) VALUES ( 'SPACE' || lpad(SPACE_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00002', 'EMP00004', '台北市南港區忠孝東路七段371號B1AF南側廣場出口2旁', '收多易共同工作空間', '共用工作空間', '投影機', '30', '租借單位或團體應盡善良使用人之責任。', '24小時內取消您的預訂', 'T', '2020/02/01', '2020/02/01' );
INSERT INTO SPACE ( SPACE_ID, MEMBER_ID, EMP_ID, SPACE_ADDRESS, SPACE_NAME, SPACE_TYPE, SPACE_EQUMENT, SPACE_CONTAIN, SPACE_RULE, SPACE_REFUND, SPACE_STATUS, SPACE_SIGNUP_DATE, SPACE_ONSALE_DATE, SPACE_OFFSALE_DATE) VALUES ( 'SPACE' || lpad(SPACE_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00004', 'EMP00003', '台北市大安區東豐街66號3樓307室', '大安小樹屋', '親子活動', '冷氣', '15', '租借單位或團體應盡善良使用人之責任。', '24小時內取消您的預訂', 'F' ,'2020/05/13', '2020/05/23', '2020/07/25' );
------------------------------------------------------------------------------

CREATE TABLE ORDER_MASTER (
ORDER_MASTER_ID  VARCHAR2(20) NOT NULL,
MEMBER_ID   VARCHAR2(20) NOT NULL,
ORDER_CREATE_DATE   DATE NOT NULL,
ORDER_AMOUNT NUMBER(6) NOT NULL,
ORDER_STATUS   CHAR(1) NOT NULL,
ORDER_STATUS_EMP   VARCHAR2(20),
ORDER_STATUS_COMM   VARCHAR2(100),
CONSTRAINT ORDER_MASTER_PK PRIMARY KEY (ORDER_MASTER_ID),
CONSTRAINT ORDER_MASTER_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

CREATE SEQUENCE ORDER_MASTER_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
------------------------------------------------------------------------------
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00001', '2020-08-01', 2000, 'T' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00002', '2020-09-01', 2000, 'T' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00003', '2020-10-01', 2000, 'T' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00004', '2020-11-01', 2000, 'T' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00002', '2020-09-01', 1750, 'P' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00003', '2020-10-01', 2100, 'R' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00003', '2020-11-01', 2100, 'C' );
INSERT INTO ORDER_MASTER(ORDER_MASTER_ID, MEMBER_ID, ORDER_CREATE_DATE, ORDER_AMOUNT, ORDER_STATUS) VALUES ( 'OMS' || lpad(ORDER_MASTER_ID_SEQ.NEXTVAL, 6, '0'), 'MEM00002', '2020-12-01', 2100, 'F' );
------------------------------------------------------------------------------

CREATE TABLE SPACE_DETAIL(
SPACE_DETAIL_ID  VARCHAR2(20) NOT NULL,
SPACE_ID   VARCHAR2(20) NOT NULL,
SPACE_DETAIL_FREEDATE   DATE NOT NULL,
SPACE_DETAIL_FREETIME_START   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
SPACE_DETAIL_FREETIME_END   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
SPACE_DETAIL_CHARGE   NUMBER(10) CHECK (SPACE_DETAIL_CHARGE >= 0) NOT NULL,
CONSTRAINT SPACE_DETAIL_PK PRIMARY KEY (SPACE_DETAIL_ID),
CONSTRAINT SPACE_DETAIL_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID)
);

CREATE SEQUENCE SPACE_DETAIL_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
---------------------------------------------------------------------------------
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-07-01','2020-07-01 01:00:00','2020-07-30 11:00:00','50');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-08-01','2020-08-01 01:00:00','2020-08-30 11:00:00','60');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-09-01','2020-09-01 01:00:00','2020-09-30 11:00:00','70');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-10-01','2020-10-01 01:00:00','2020-10-30 11:00:00','80');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-07-01','2020-07-01 01:00:00','2020-07-30 11:00:00','50');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-08-01','2020-08-01 01:00:00','2020-08-30 11:00:00','60');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-09-01','2020-09-01 01:00:00','2020-09-30 11:00:00','70');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-10-01','2020-10-01 01:00:00','2020-10-30 11:00:00','80');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-07-01','2020-07-01 01:00:00','2020-07-30 11:00:00','50');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-08-01','2020-08-01 01:00:00','2020-08-30 11:00:00','60');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-09-01','2020-09-01 01:00:00','2020-09-30 11:00:00','70');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-10-01','2020-10-01 01:00:00','2020-10-30 11:00:00','80');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-03-01','2020-03-01 01:00:00','2020-07-30 11:00:00','50');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-04-01','2020-04-01 01:00:00','2020-08-30 11:00:00','60');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-05-01','2020-05-01 01:00:00','2020-09-30 11:00:00','70');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-06-01','2020-06-01 01:00:00','2020-10-30 11:00:00','80');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00002','2020-08-14','2020-01-14 02:00:00','2020-01-17 11:00:00','60');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00003','2020-09-14','2020-02-14 03:00:00','2020-02-17 11:00:00','70');
INSERT INTO SPACE_DETAIL VALUES ('SD' || lpad(SPACE_DETAIL_ID_SEQ.NEXTVAL, 5, '0'),'SPACE00001','2020-10-14','2020-12-14 04:00:00','2020-12-17 11:00:00','80');
------------------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE ORDER_DETAIL (
ORDER_DETAIL_ID  VARCHAR2(20) NOT NULL,
ORDER_MASTER_ID  VARCHAR2(20) NOT NULL,
SPACE_DETAIL_ID  VARCHAR2(20) NOT NULL,
RENT_START_TIME TIMESTAMP NOT NULL,
RENT_END_TIME TIMESTAMP NOT NULL,
CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_DETAIL_ID),
CONSTRAINT ORDER_DETAIL_ORDER_MASTER_FK FOREIGN KEY (ORDER_MASTER_ID) REFERENCES ORDER_MASTER (ORDER_MASTER_ID),
CONSTRAINT ORDER_DETAIL_SPACE_DETAIL_FK FOREIGN KEY (SPACE_DETAIL_ID) REFERENCES SPACE_DETAIL (SPACE_DETAIL_ID)
);

CREATE SEQUENCE ORDER_DETAIL_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
----------------------------------------------------------------------------------------
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000001', 'SD00001', '2020-07-02 15:30', '2020-09-18 18:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000002', 'SD00002', '2020-08-03 10:00', '2020-09-18 17:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000003', 'SD00003', '2020-09-04 11:30', '2020-09-18 15:30' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000004', 'SD00004', '2020-07-19 16:30', '2020-09-20 18:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000005', 'SD00005', '2020-08-11 11:00', '2020-09-12 17:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000001', 'SD00006', '2020-09-17 12:30', '2020-09-18 15:30' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000002', 'SD00001', '2020-07-12 05:30', '2020-09-13 18:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000003', 'SD00002', '2020-08-01 00:00', '2020-09-01 17:00' );
INSERT INTO ORDER_DETAIL(ORDER_DETAIL_ID, ORDER_MASTER_ID, SPACE_DETAIL_ID, RENT_START_TIME, RENT_END_TIME) VALUES ( 'OD' || lpad(ORDER_DETAIL_ID_SEQ.NEXTVAL, 7, '0'), 'OMS000004', 'SD00002', '2020-09-14 01:30', '2020-09-15 15:30' );
----------------------------------------------------------------------------------------

CREATE TABLE SPACE_PHOTO (
SPACE_PHOTO_ID  VARCHAR2(20) NOT NULL,
SPACE_ID  VARCHAR2(20) NOT NULL,
SPACE_PHOTO  BLOB,
CONSTRAINT SPACE_PHOTO_PK PRIMARY KEY (SPACE_PHOTO_ID),
CONSTRAINT SPACE_PHOTO_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID)
);

CREATE SEQUENCE SPACE_PHOTO_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
--------------------------------------------------------------------------------------------
INSERT INTO SPACE_PHOTO(SPACE_PHOTO_ID, SPACE_ID) VALUES ( 'SPACEPHOTO' || lpad(SPACE_PHOTO_ID_SEQ.NEXTVAL, 7, '0'), 'SPACE00002' );
INSERT INTO SPACE_PHOTO(SPACE_PHOTO_ID, SPACE_ID) VALUES ( 'SPACEPHOTO' || lpad(SPACE_PHOTO_ID_SEQ.NEXTVAL, 7, '0'), 'SPACE00001' );
INSERT INTO SPACE_PHOTO(SPACE_PHOTO_ID, SPACE_ID) VALUES ( 'SPACEPHOTO' || lpad(SPACE_PHOTO_ID_SEQ.NEXTVAL, 7, '0'), 'SPACE00003' );
--------------------------------------------------------------------------------------------

CREATE TABLE MEMBER_COMMENT(
MEMBER_COMMENT_ID  VARCHAR2(20) NOT NULL,
MEMBER_A_ID   VARCHAR2(20) NOT NULL,
MEMBER_B_ID  VARCHAR2(20) NOT NULL,
MEMBER_COMMENT_CONTENT   VARCHAR2(300) NOT NULL,
MEMBER_COMMENT_LEVEL   NUMBER(4,2) NOT NULL,
MEMBER_COMMENT_DATE   DATE NOT NULL,
MEMBER_COMMENT_STATUS   CHAR(1) NOT NULL,
MEMBER_COMMENT_STATUS_EMP   VARCHAR2(20),
MEMBER_COMMENT_STATUS_COMM   VARCHAR2(100),
CONSTRAINT MEMBER_COMMENT_PK PRIMARY KEY (MEMBER_COMMENT_ID),
CONSTRAINT MEMBER_COMMENT_MEMBER_A_FK FOREIGN KEY (MEMBER_A_ID) REFERENCES MEMBER (MEMBER_ID),
CONSTRAINT MEMBER_COMMENT_MEMBER_B_FK FOREIGN KEY (MEMBER_B_ID) REFERENCES MEMBER (MEMBER_ID)
);

CREATE SEQUENCE MEMBER_COMMENT_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
------------------------------------------------------------------------------------------------------
INSERT INTO MEMBER_COMMENT ( MEMBER_COMMENT_ID, MEMBER_A_ID, MEMBER_B_ID, MEMBER_COMMENT_CONTENT, MEMBER_COMMENT_LEVEL, MEMBER_COMMENT_DATE, MEMBER_COMMENT_STATUS ) VALUES ( 'MCOMMENT' || lpad(MEMBER_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00001', 'MEM00004', '服務優良，價格公道合理！租借的道具也多，景都搭得很美，很多小心思～整體都很棒', 4.3, '2020-08-25', 'Y' );
INSERT INTO MEMBER_COMMENT ( MEMBER_COMMENT_ID, MEMBER_A_ID, MEMBER_B_ID, MEMBER_COMMENT_CONTENT, MEMBER_COMMENT_LEVEL, MEMBER_COMMENT_DATE, MEMBER_COMMENT_STATUS ) VALUES ( 'MCOMMENT' || lpad(MEMBER_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00005', 'MEM00002', '棚景多樣而且都很美！員工也很親切', 5.0, '2020-09-03', 'Y' );
INSERT INTO MEMBER_COMMENT ( MEMBER_COMMENT_ID, MEMBER_A_ID, MEMBER_B_ID, MEMBER_COMMENT_CONTENT, MEMBER_COMMENT_LEVEL, MEMBER_COMMENT_DATE, MEMBER_COMMENT_STATUS ) VALUES ( 'MCOMMENT' || lpad(MEMBER_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'MEM00001', 'MEM00003', '提供的場地過於髒亂，且態度不佳', 2.5, '2020-09-05', 'Y' );
------------------------------------------------------------------------------------------------------

CREATE TABLE SPACE_COMMENT(
SPACE_COMMENT_ID  VARCHAR2(20) NOT NULL,
SPACE_ID   VARCHAR2(20) NOT NULL,
MEMBER_ID  VARCHAR2(20) NOT NULL,
SPACE_COMMENT_CONTENT VARCHAR2(500) NOT NULL,
SPACE_COMMENT_LEVEL   NUMBER(4,2) NOT NULL,
SPACE_COMMENT_DATE   DATE NOT NULL,
SPACE_COMMENT_STATUS   CHAR(1) NOT NULL,
SPACE_COMMENT_STATUS_EMP   VARCHAR2(20),
SPACE_COMMENT_STATUS_COMM   VARCHAR2(100),
CONSTRAINT SPACE_COMMENT_PK PRIMARY KEY (SPACE_COMMENT_ID),
CONSTRAINT SPACE_COMMENT_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID),
CONSTRAINT SPACE_COMMENT_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

CREATE SEQUENCE SPACE_COMMENT_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
----------------------------------------------------------------------------------------------------------
INSERT INTO SPACE_COMMENT( SPACE_COMMENT_ID, SPACE_ID, MEMBER_ID, SPACE_COMMENT_CONTENT, SPACE_COMMENT_LEVEL, SPACE_COMMENT_DATE, SPACE_COMMENT_STATUS ) VALUES ( 'SCOMMENT' || lpad(SPACE_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'SPACE00003', 'MEM00001', '該有的設備都有，離捷運站走路五分鐘左右而已', 5.0, '2019-12-30', 'Y' );
INSERT INTO SPACE_COMMENT( SPACE_COMMENT_ID, SPACE_ID, MEMBER_ID, SPACE_COMMENT_CONTENT, SPACE_COMMENT_LEVEL, SPACE_COMMENT_DATE, SPACE_COMMENT_STATUS ) VALUES ( 'SCOMMENT' || lpad(SPACE_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'SPACE00001', 'MEM00005', '這個訓練場地極為陽春，幾乎可用家徒四壁來形容。上課教室沒有桌子，只能放置20張左右的椅子。', 2.5, '2020-06-28', 'Y' );
INSERT INTO SPACE_COMMENT( SPACE_COMMENT_ID, SPACE_ID, MEMBER_ID, SPACE_COMMENT_CONTENT, SPACE_COMMENT_LEVEL, SPACE_COMMENT_DATE, SPACE_COMMENT_STATUS ) VALUES ( 'SCOMMENT' || lpad(SPACE_COMMENT_ID_SEQ.NEXTVAL, 5, '0'), 'SPACE00002', 'MEM00003', '感覺很有創意，也很用心在經營', 4.5, '2020-09-12', 'Y' );
----------------------------------------------------------------------------------------------------------

CREATE TABLE MEMBER_FAVORITE (
MEMBER_FAVORITE_ID  VARCHAR2(20) NOT NULL,
MEMBER_ID  VARCHAR2(20) NOT NULL,
SPACE_ID  VARCHAR2(20) NOT NULL,
CONSTRAINT MEMBER_FAVORITE_PK PRIMARY KEY (MEMBER_FAVORITE_ID),
CONSTRAINT MEMBER_FAVORITE_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
CONSTRAINT MEMBER_FAVORITE_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID)
);

CREATE SEQUENCE MEMBER_FAVORITE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;
----------------------------------------------------------------------------------------------------
INSERT INTO MEMBER_FAVORITE( MEMBER_FAVORITE_ID, MEMBER_ID, SPACE_ID) VALUES ( 'FAVORITE' || lpad(MEMBER_FAVORITE_ID_SEQ.NEXTVAL, 5, '0' ), 'MEM00001', 'SPACE00002' );
INSERT INTO MEMBER_FAVORITE( MEMBER_FAVORITE_ID, MEMBER_ID, SPACE_ID) VALUES ( 'FAVORITE' || lpad(MEMBER_FAVORITE_ID_SEQ.NEXTVAL, 5, '0' ), 'MEM00005', 'SPACE00001' );
INSERT INTO MEMBER_FAVORITE( MEMBER_FAVORITE_ID, MEMBER_ID, SPACE_ID) VALUES ( 'FAVORITE' || lpad(MEMBER_FAVORITE_ID_SEQ.NEXTVAL, 5, '0' ), 'MEM00001', 'SPACE00003' );
----------------------------------------------------------------------------------------------------

CREATE TABLE FORM_LIST(
FORM_LIST_ID  VARCHAR2(20) NOT NULL,
MEMBER_ID   VARCHAR2(20) NOT NULL,
EMP_ID  VARCHAR2(20),
FORM_CREATE_DATE  DATE NOT NULL,
FORM_LIST_TYPE   VARCHAR2(20) NOT NULL,
FORM_TITLE   VARCHAR2(90) NOT NULL,
FORM_CONTENT   CLOB,
FORM_STATUS VARCHAR2(20) NOT NULL,
FORM_SOLU VARCHAR2(200),
FORM_SOLU_DATE  DATE,
CONSTRAINT FORM_LIST_PK PRIMARY KEY (FORM_LIST_ID),
CONSTRAINT FORM_LIST_MEMBER_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
CONSTRAINT FORM_LIST_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMP (EMP_ID)
);

CREATE SEQUENCE FORM_LIST_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

---------------------------------------------------------------------------------------------------------
INSERT INTO FORM_LIST(FORM_LIST_ID, MEMBER_ID, EMP_ID, FORM_CREATE_DATE, FORM_LIST_TYPE, FORM_TITLE, FORM_CONTENT, FORM_STATUS) VALUES ( 'FORMS' || lpad(FORM_LIST_ID_SEQ.NEXTVAL, 7, '0'), 'MEM00003', 'EMP00002', '2020-01-27', '投訴', '租借問題相關', '請問你們的預約會保留多久呢', 'undo');
INSERT INTO FORM_LIST(FORM_LIST_ID, MEMBER_ID, EMP_ID, FORM_CREATE_DATE, FORM_LIST_TYPE, FORM_TITLE, FORM_CONTENT, FORM_STATUS) VALUES ( 'FORMS' || lpad(FORM_LIST_ID_SEQ.NEXTVAL, 7, '0'), 'MEM00001', 'EMP00002', '2020-09-17','客服', '網站錯誤回報', '剛剛的網頁存取行為發生了問題', 'undo');
INSERT INTO FORM_LIST(FORM_LIST_ID, MEMBER_ID, EMP_ID, FORM_CREATE_DATE, FORM_LIST_TYPE, FORM_TITLE, FORM_CONTENT, FORM_STATUS) VALUES ( 'FORMS' || lpad(FORM_LIST_ID_SEQ.NEXTVAL, 7, '0'), 'MEM00003',  'EMP00001','2020-09-19', '檢舉', '投訴', '場地髒亂，場主不處理', 'undo');
---------------------------------------------------------------------------------------------------------

CREATE TABLE FORM_LIST_FILE (
FORM_LIST_FILE_ID  VARCHAR2(20) NOT NULL,
FORM_LIST_ID  VARCHAR2(20) NOT NULL,
FORM_LIST_FILE  BLOB,
CONSTRAINT FORM_LIST_FILE_PK PRIMARY KEY (FORM_LIST_FILE_ID),
CONSTRAINT FORM_LIST_FILE_FORM_LIST_FK FOREIGN KEY (FORM_LIST_ID) REFERENCES FORM_LIST (FORM_LIST_ID)
);

CREATE SEQUENCE FORM_LIST_FILE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;




COMMIT;